import { KeyRound, Save, TriangleAlert, UserPlus } from "lucide-react";
import { type FormEvent, useState } from "react";
import { useTranslation } from "react-i18next";
import type { Account, Role } from "../../../../shared/types";
import { CopyRow } from "../../../components/CopyRow";
import { Button } from "../../../components/ui/button";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogTitle } from "../../../components/ui/dialog";
import { SelectField } from "../../../components/ui/select-field";
import { TextField } from "../../../components/ui/text-field";
import type { AccountFieldErrors, IssuedPassword } from "../useAccounts";

type AccountFormDialogProps = {
  // "new" = create; an account = edit it; null = closed.
  target: Account | "new" | null;
  errors: AccountFieldErrors;
  onClose: () => void;
  onCreate: (fields: { username: string; display_name: string; role: Role }) => Promise<boolean>;
  onUpdate: (account: Account, patch: { display_name?: string; role?: Role }) => Promise<boolean>;
};

// Create or edit an account. The username is fixed after creation here (the API allows renaming,
// but a changed login name is a surprise for the member); the password is always generated by the
// server and shown once afterwards.
export function AccountFormDialog({ target, errors, onClose, onCreate, onUpdate }: AccountFormDialogProps) {
  const editing = target !== null && target !== "new" ? target : null;
  return (
    <Dialog open={target !== null} onOpenChange={(open) => !open && onClose()}>
      <DialogContent>
        {/* Keyed so each opening starts from the account's current values. */}
        <AccountForm key={editing?.code ?? "new"} editing={editing} errors={errors} onClose={onClose} onCreate={onCreate} onUpdate={onUpdate} />
      </DialogContent>
    </Dialog>
  );
}

function AccountForm({
  editing,
  errors,
  onClose,
  onCreate,
  onUpdate,
}: Omit<AccountFormDialogProps, "target"> & { editing: Account | null }) {
  const { t } = useTranslation();
  const [username, setUsername] = useState("");
  const [displayName, setDisplayName] = useState(editing?.display_name ?? "");
  const [role, setRole] = useState<Role>(editing?.role ?? "MEMBER");
  const [busy, setBusy] = useState(false);

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    setBusy(true);
    const done = editing
      ? await onUpdate(editing, {
          ...(displayName.trim() !== editing.display_name && { display_name: displayName.trim() }),
          ...(role !== editing.role && { role }),
        })
      : await onCreate({ username: username.trim(), display_name: displayName.trim(), role });
    setBusy(false);
    if (done) onClose();
  };

  return (
    <>
      <DialogTitle>{editing ? t("accounts.editTitle", { user: editing.display_name }) : t("accounts.newTitle")}</DialogTitle>
      <DialogDescription>{editing ? `@${editing.username}` : t("accounts.newBody")}</DialogDescription>
      <form method="post" onSubmit={(event) => void submit(event)} className="flex flex-col gap-4">
        {!editing && (
          <TextField
            label={t("accounts.username")}
            value={username}
            onChange={(event) => setUsername(event.target.value)}
            autoComplete="off"
            autoCapitalize="none"
            spellCheck={false}
            error={errors.username}
          />
        )}
        <TextField label={t("accounts.displayName")} value={displayName} onChange={(event) => setDisplayName(event.target.value)} maxLength={64} error={errors.display_name} />
        <SelectField label={t("accounts.role")} value={role} onChange={(event) => setRole(event.target.value as Role)} error={errors.role}>
          <option value="MEMBER">{t("role.MEMBER")}</option>
          <option value="ADMIN">{t("role.ADMIN")}</option>
        </SelectField>
        <div className="flex justify-end gap-2">
          <DialogClose asChild>
            <Button variant="text">{t("confirm.cancel")}</Button>
          </DialogClose>
          <Button type="submit" disabled={busy}>
            {editing ? <Save aria-hidden="true" /> : <UserPlus aria-hidden="true" />}
            {editing ? t("accounts.save") : t("accounts.create")}
          </Button>
        </div>
      </form>
    </>
  );
}

// The one time a password is visible. Closing it — by button, Escape or the scrim — drops it.
export function PasswordDialog({ issued, onClose }: { issued: IssuedPassword | null; onClose: () => void }) {
  const { t } = useTranslation();
  return (
    <Dialog open={issued !== null} onOpenChange={(open) => !open && onClose()}>
      <DialogContent>
        <DialogTitle className="flex items-center gap-2">
          <KeyRound className="size-6 shrink-0 text-primary" aria-hidden="true" />
          {issued?.reset ? t("accounts.resetDoneTitle") : t("accounts.createdTitle")}
        </DialogTitle>
        <DialogDescription>{t("accounts.passwordBody", { user: issued?.account.display_name ?? "" })}</DialogDescription>
        {issued && (
          <dl className="divide-y divide-outline-variant/50 rounded-2xl bg-surface-container-lowest px-4">
            <CopyRow label={t("accounts.username")} value={issued.account.username} />
            <CopyRow label={t("accounts.password")} value={issued.password} />
          </dl>
        )}
        <p className="flex items-start gap-2 rounded-2xl bg-warning-container px-4 py-3 text-sm font-medium text-on-warning-container">
          <TriangleAlert className="mt-0.5 size-4 shrink-0" aria-hidden="true" />
          {t("accounts.passwordOnce")}
        </p>
        <DialogClose asChild>
          <Button>{t("accounts.passwordSaved")}</Button>
        </DialogClose>
      </DialogContent>
    </Dialog>
  );
}
